### ISSUE TITLE
Dependency role names

### ISSUE THREAD

**Issue by nsticco** [andrewrothstein/ansible-haskell#1]
I got the following response using this role:
```
ERROR! role definitions must contain a role name

The error appears to have been in '/etc/ansible/roles/andrewrothstein.haskell/meta/main.yml': line 33, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

dependencies:
  - src: andrewrothstein.unarchive-deps
    ^ here
```
I was able to get rid of it by adding a name line underneath each dependency. Seems like maybe Ansible changed its requirements.

**Comment by andrewrothstein** [comment]
what version of Ansible are you using? If you look at the [Travis build](https://travis-ci.org/andrewrothstein/ansible-haskell) you can see the role being applied with Ansible v2.4.3.0 without issue.

**Comment by nsticco** [comment]
This was with Ansible 2.0.0.2 on Ubuntu 16.04. Maybe it's an issue with an older version then.
